[project]
name = "sadpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.1",
    "pandas>=2.3.3",
    "torch>=2.9.1",
    "wandb>=0.23.1",
]
